<%@ Page Language="VB" AutoEventWireup="false" CodeFile="Default.aspx.vb" Inherits="_Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    </head>
    <style>
    asp:MenuItem
    {
        width =300px;
        }
    
    </style>
 <!-- bootstrapt -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

   <link rel="icon"
      href="https://fitnessfactorymaine.com/wp-content/uploads/2019/01/cropped-FF-Logo-Red-and-Black-32x32.png"
      sizes="32x32">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
      integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous" referrerpolicy="no-referrer" />

<body>
   
    <form id="form1" runat="server">
    <div>
        <asp:Menu ID="Menu1" runat="server" Orientation="Horizontal" Width="900px">
            <Items>
                <asp:MenuItem Text="home" Value="home">
                </asp:MenuItem>
                <asp:MenuItem Text="Contact" Value="Contact"></asp:MenuItem>
                <asp:MenuItem Text="about" Value="about"></asp:MenuItem>
                <asp:MenuItem Text="login" Value="login"></asp:MenuItem>
            </Items>
        </asp:Menu>
    </div>
    <div class="container">
        <asp:Label ID="Label1" runat="server" Text="name"></asp:Label>
        <asp:TextBox ID="TextBox1" class="form-control"
            runat="server"></asp:TextBox>
             <asp:Label ID="Label2" runat="server" Text="number"></asp:Label>
        <asp:TextBox ID="TextBox2" class="form-control"
            runat="server"></asp:TextBox>
     <asp:Label ID="Label3" runat="server" Text="add"></asp:Label>
        <asp:TextBox ID="TextBox3" class="form-control"
            runat="server"></asp:TextBox>
        <asp:Button ID="Button1" runat="server" Text="submit" />
        <asp:GridView ID="GridView1"
            runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                <asp:BoundField DataField="add" HeaderText="add" SortExpression="add" />
                <asp:BoundField DataField="contact" HeaderText="contact" 
                    SortExpression="contact" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ConnectionString2 %>" 
            SelectCommand="SELECT * FROM [try]"
            UpdateCommand="update [try] set [name]=@name"
            >
            <UpdateParameters>
                <asp:Parameter Name="name" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <asp:Login ID="Login1" runat="server">
        </asp:Login>
    </div>
    </form>
</body>
</html>
