<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="user.aspx.vb" Inherits="WebApplication1.user" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>

<body>
    <form id="form1" runat="server">
    <div>
        
    </div>
    <div class="view" style="margin: auto;min-height: 400px;width: 700px;margin-top: 60px;">
    <asp:Button ID="Button1" runat="server"   Text="Add User" 
            PostBackUrl="~/contact.aspx" BackColor="#FF0066" />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id" 
            DataSourceID="SqlDataSource2" AllowPaging="True" AllowSorting="True" 
            BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" 
            CellPadding="3" ForeColor="Black" GridLines="Vertical" Width="994px" 
            Caption="Users" CellSpacing="2">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
            
                <asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" 
                    SortExpression="id" />
                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                <asp:BoundField DataField="contact" HeaderText="contact" 
                    SortExpression="contact" />
                <asp:BoundField DataField="add" HeaderText="add" SortExpression="add" />
                <asp:BoundField DataField="state" HeaderText="state" SortExpression="state" />
                <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                <asp:BoundField DataField="plan" HeaderText="plan" SortExpression="plan" />
                <asp:BoundField DataField="payment" HeaderText="payment" 
                    SortExpression="payment" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server"  
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            SelectCommand="SELECT * FROM [users]"
            UpdateCommand="update [users] set [name]=@name,[email]=@email,[contact]=@contact,[state]=@state,[city]=@city,[plan]=@plan,[payment]=@payment,[add]=@add where [id]=@id"
            DeleteCommand="DELETE FROM [users] where [id]=@id"

            
            ></asp:SqlDataSource>
    </div>
    </form>
</body>
</html>
